//Try catch se usa mucho con el asyn await
try 
{
	console.log(2+2);
	hola();
} 
catch(e) 
{
	console.log(e);
}

console.log(2+64);